name: Upload Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - uses: Gr1N/setup-poetry@v8

      - name: Get poetry cache dir
        id: poetry-cache
        run: |
          echo "::set-output name=dir::$(poetry config cache-dir)"

      - name: Poetry cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key: poetry-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Build pixy
        run: poetry build

      - name: Publish pixy
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_API_KEY }}
