name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v7
      
      - name: Install dependencies
        run: poetry install -vvv

      - name: Get poetry cache dir
        id: poetry-cache
        run: |
          echo "::set-output name=dir::$(poetry config cache-dir)"

      - name: Poetry cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key: poetry-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Code style
        run: make style-check

      - name: Unit tests
        run: make test
        
      - name: Check types
        run: make types

      - name: Upload coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
